PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl:     <http://www.w3.org/2002/07/owl#> 
PREFIX lo17:    <http://www.owl-ontologies.com/lo17#>  

SELECT DISTINCT ?leg1 ?numero
WHERE {
  ?bull rdf:type lo17:Bulletin ;
  lo17:hasNumero ?numero ;
  lo17:hasImage ?image1 ,
  ?image2 ,
  ?image3 .
  ?image1 lo17:legendeImage ?leg1 .
  ?image2 lo17:legendeImage ?leg2 .
  ?image3 lo17:legendeImage ?leg3 .
  FILTER(?image1 != ?image2 &&  ?image3 != ?image2 && ?image1 != ?image3)
} 

